// react/src/pages/ListaDeCards.tsx
import { useState } from 'react'
import { Modal, ProgressBar } from 'react-bootstrap'
import { CARD_AVATARS, FILE_CARDS } from '../data/examples'
import { ItemActions } from '../components/ItemActions'
import { LoadingOverlay, MdiIcon, PageHeader } from '../components/shared'

type ModalProps = {
  show: boolean
  onHide: () => void
}

function FileModal({ show, onHide }: ModalProps) {
  return (
    <Modal show={show} onHide={onHide}>
      <Modal.Header closeButton>
        <Modal.Title as="h4">Salvando arquivo</Modal.Title>
      </Modal.Header>

      <form>
        <Modal.Body>
          <div className="row">
            <div className="col-12">
              <label className="visually-hidden" htmlFor="anexoInputModal">
                Arquivo
              </label>
              <div className="input-group">
                <input
                  id="anexoInputModal"
                  type="text"
                  className="form-control"
                  placeholder="Escolha um arquivo de seu dispositivo"
                  aria-label="Escolha um arquivo de seu dispositivo"
                  disabled
                />
                <label className="btn btn-secondary px-3 position-relative btn-sm" htmlFor="btnAnexoModal">
                  <input id="btnAnexoModal" className="visually-hidden" type="file" />
                  <MdiIcon name="paperclip" />
                  <span className="visually-hidden">Selecionar arquivo</span>
                </label>
              </div>
            </div>

            <div className="col-12 py-3">
              <ProgressBar now={80} />
              <p className="m-0 mt-1 text-muted">Carregando...</p>
            </div>
          </div>
        </Modal.Body>

        <Modal.Footer>
          <button type="button" className="btn btn-primary" onClick={onHide}>
            Salvar
          </button>
          <button type="button" className="btn btn-secondary" onClick={onHide}>
            Cancelar
          </button>
        </Modal.Footer>
      </form>
    </Modal>
  )
}

export function ListaDeCards() {
  const [showModal, setShowModal] = useState(false)

  return (
    <>
      <LoadingOverlay />
      <PageHeader title="Lista de cards">
        <div className="col-12 col-lg-auto my-3 my-lg-0">
          <nav aria-label="breadcrumb">
            <ol className="breadcrumb">
              <li className="breadcrumb-item">
                <button type="button" className="btn btn-link p-0">
                  Grupo
                </button>
              </li>
              <li className="breadcrumb-item">
                <button type="button" className="btn btn-link p-0">
                  Subgrupo
                </button>
              </li>
              <li className="breadcrumb-item active" aria-current="page">
                Item
              </li>
            </ol>
          </nav>
        </div>
      </PageHeader>

      <div className="row align-items-center mb-3">
        <div className="col">
          <div className="btn-group">
            <button
              type="button"
              className="btn btn-sm btn-success"
              onClick={() => setShowModal(true)}
              aria-label="Adicionar arquivo"
            >
              <MdiIcon name="plus" className="h6 m-0 me-1" />
              Arquivo
            </button>
          </div>
        </div>

        <div className="col-auto">
          <div className="d-block pe-1">
            {CARD_AVATARS.map((avatar) => (
              <div className="d-inline-block me-n1" key={avatar}>
                <img className="rounded-circle border" width="30" height="30" alt="" src={avatar} />
              </div>
            ))}
          </div>
        </div>

        <div className="col-12 col-lg-3 my-3 my-lg-0">
          <label className="visually-hidden" htmlFor="buscaCards">
            Pesquisar na lista de cards
          </label>
          <div className="input-group">
            <input
              id="buscaCards"
              className="form-control"
              type="search"
              placeholder="O que você está buscando?"
            />
            <button type="button" className="btn btn-secondary" aria-label="Pesquisar">
              <MdiIcon name="magnify" />
            </button>
          </div>
        </div>
      </div>

      <div className="row">
        {FILE_CARDS.map((file) => (
          <div className="col-12 col-sm-6 col-md-3 col-lg-2" key={file.id}>
            <div className="card mb-2">
              <div className="card-body p-0 overflow-hidden file-card-preview">
                <img className="w-100 file-card-image" src={file.imageUrl} alt="" />
              </div>
              <div className="card-footer bg__gray--l40">
                <div className="row m-0 align-items-center">
                  <div className="col-10">
                    <p className="text-truncate m-0">{file.title}</p>
                  </div>
                  <div className="col-2 text-end">
                    <ItemActions id={file.id} ariaLabel="Abrir ações do arquivo" size="sm" />
                  </div>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>

      <FileModal show={showModal} onHide={() => setShowModal(false)} />
    </>
  )
}

// app-vue/src/pages/ListaDeCards.vue
<template>
  <div>
  <LoadingOverlay />
  <PageHeader title="Lista de cards">
    <div class="col-12 col-lg-auto my-3 my-lg-0">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <button type="button" class="btn btn-link p-0">Grupo</button>
          </li>
          <li class="breadcrumb-item">
            <button type="button" class="btn btn-link p-0">Subgrupo</button>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Item</li>
        </ol>
      </nav>
    </div>
  </PageHeader>

  <div class="row align-items-center mb-3">
    <div class="col">
      <div class="btn-group">
        <button
          type="button"
          class="btn btn-sm btn-success"
          aria-label="Adicionar arquivo"
          @click="openModal"
        >
          <MdiIcon name="plus" extra-class="h6 m-0 me-1" />
          Arquivo
        </button>
      </div>
    </div>

    <div class="col-auto">
      <div class="d-block pe-1">
        <div v-for="avatar in CARD_AVATARS" :key="avatar" class="d-inline-block me-n1">
          <img class="rounded-circle border" width="30" height="30" alt="" :src="avatar" />
        </div>
      </div>
    </div>

    <div class="col-12 col-lg-3 my-3 my-lg-0">
      <label class="visually-hidden" for="buscaCards">Pesquisar na lista de cards</label>
      <div class="input-group">
        <input
          id="buscaCards"
          class="form-control"
          type="search"
          placeholder="O que você está buscando?"
        />
        <button type="button" class="btn btn-secondary" aria-label="Pesquisar">
          <MdiIcon name="magnify" />
        </button>
      </div>
    </div>
  </div>

  <div class="row">
    <div
      v-for="file in FILE_CARDS"
      :key="file.id"
      class="col-12 col-sm-6 col-md-3 col-lg-2"
    >
      <div class="card mb-2">
        <div class="card-body p-0 overflow-hidden file-card-preview">
          <img class="w-100 file-card-image" :src="file.imageUrl" alt="" />
        </div>
        <div class="card-footer bg__gray--l40">
          <div class="row m-0 align-items-center">
            <div class="col-10">
              <p class="text-truncate m-0">{{ file.title }}</p>
            </div>
            <div class="col-2 text-end">
              <ItemActions :id="file.id" aria-label="Abrir ações do arquivo" />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal -->
  <div ref="modalRef" class="modal fade" tabindex="-1" aria-labelledby="fileModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="fileModalLabel">Salvando arquivo</h4>
          <button type="button" class="btn-close" @click="closeModal" aria-label="Fechar"></button>
        </div>

        <form>
          <div class="modal-body">
            <div class="row">
              <div class="col-12">
                <label class="visually-hidden" for="anexoInputModal">Arquivo</label>
                <div class="input-group">
                  <input
                    id="anexoInputModal"
                    type="text"
                    class="form-control"
                    placeholder="Escolha um arquivo de seu dispositivo"
                    aria-label="Escolha um arquivo de seu dispositivo"
                    disabled
                  />
                  <label class="btn btn-secondary px-3 position-relative btn-sm" for="btnAnexoModal">
                    <input id="btnAnexoModal" class="visually-hidden" type="file" />
                    <MdiIcon name="paperclip" />
                    <span class="visually-hidden">Selecionar arquivo</span>
                  </label>
                </div>
              </div>

              <div class="col-12 py-3">
                <div class="progress">
                  <div
                    class="progress-bar"
                    role="progressbar"
                    style="width: 80%"
                    aria-valuenow="80"
                    aria-valuemin="0"
                    aria-valuemax="100"
                  ></div>
                </div>
                <p class="m-0 mt-1 text-muted">Carregando...</p>
              </div>
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-primary" @click="closeModal">Salvar</button>
            <button type="button" class="btn btn-secondary" @click="closeModal">Cancelar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { Modal } from 'bootstrap'
import { CARD_AVATARS, FILE_CARDS } from '@/data/examples'
import LoadingOverlay from '@/components/LoadingOverlay.vue'
import PageHeader from '@/components/PageHeader.vue'
import MdiIcon from '@/components/MdiIcon.vue'
import ItemActions from '@/components/ItemActions.vue'

const modalRef = ref<HTMLElement | null>(null)
let bsModal: Modal | null = null

onMounted(() => {
  bsModal = new Modal(modalRef.value!)
})

onUnmounted(() => {
  bsModal?.dispose()
})

function openModal() {
  bsModal?.show()
}

function closeModal() {
  bsModal?.hide()
}
</script>
