// app-angular/src/app/sem-registros/sem-registros.component.ts
import { NgOptimizedImage } from '@angular/common';
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-sem-registros',
  imports: [NgOptimizedImage, RouterLink],
  templateUrl: './sem-registros.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SemRegistrosComponent {}

<div class="spinner-grow-backdrop loader-fadeout">
  <div class="spinner-grow"></div>
</div>

<div class="row align-items-center py-3">
  <div class="col">
    <h4 class="m-0">Sem registros</h4>
  </div>
</div>

<div class="row">
  <div class="col-12 text-center my-5">
    <img
      ngSrc="img/ilustracoes_semregistros.svg"
      width="349"
      height="276"
      class="img-fluid mb-5"
      alt="Ilustração indicando ausência de registros"
    />
    <p class="h5 mb-0">
      Ainda não há itens por aqui.
      <a routerLink="/formulario">Adicionar</a>
    </p>
  </div>
</div>

// app-vue/src/pages/SemRegistros.vue
<template>
  <div>
  <LoadingOverlay />
  <PageHeader title="Sem registros" />

  <div class="row">
    <div class="col-12 text-center my-5">
      <img
        src="/img/ilustracoes_semregistros.svg"
        width="349"
        height="276"
        class="img-fluid mb-5"
        alt="Ilustração indicando ausência de registros"
      />
      <p class="h5 mb-0">
        Ainda não há itens por aqui. <RouterLink to="/formulario">Adicionar</RouterLink>
      </p>
    </div>
  </div>
  </div>
</template>

<script setup lang="ts">
import { RouterLink } from 'vue-router'
import LoadingOverlay from '@/components/LoadingOverlay.vue'
import PageHeader from '@/components/PageHeader.vue'
</script>
