// react/src/App.tsx
import { useEffect, useMemo, useRef } from 'react'
import {
  BrowserRouter,
  Navigate,
  Route,
  Routes,
  useLocation,
  useNavigate,
} from 'react-router-dom'
import {
  AUTHORIZATION,
  MENU_OPTIONS,
  MENU_ROUTE_ALIASES,
  UTILITY_OPTIONS,
} from './data/examples'
import type {
  IdentificadorOpcaoMenu,
  OpcaoMenuSelecionadaEvent,
} from '@betha-plataforma/estrutura-componentes/dist/types/components/app/app.interfaces'
import type { NotificacaoComLinkEvent } from '@betha-plataforma/estrutura-componentes/dist/types/components/notificacoes/notificacoes.interfaces'
import type { OpcaoUtilitarioSelecionadaEvent } from '@betha-plataforma/estrutura-componentes/dist/types/components/utilitarios/utilitarios.interfaces'
import type { AuthorizationConfig } from '@betha-plataforma/estrutura-componentes/dist/types/global/interfaces'
import { Configuracoes } from './pages/Configuracoes'
import { Dashboard } from './pages/Dashboard'
import { Formulario } from './pages/Formulario'
import { ListaDeCards } from './pages/ListaDeCards'
import { Listagem } from './pages/Listagem'
import { SelecaoContexto } from './pages/SelecaoContexto'
import { SemRegistros } from './pages/SemRegistros'
import { Timeline } from './pages/Timeline'
import { VisaoGeral } from './pages/VisaoGeral'
import { Wizard } from './pages/Wizard'
import './App.css'

function isAbsoluteUrl(text: string) {
  try {
    new URL(text)
    return true
  } catch {
    return false
  }
}

function matchesRoute(currentRoute: string, menuRoute: string) {
  if (menuRoute === '/') {
    return currentRoute === '/'
  }

  return currentRoute === menuRoute || currentRoute.startsWith(`${menuRoute}/`)
}

function findActiveMenuId(pathname: string): IdentificadorOpcaoMenu | undefined {
  for (const [menuId, aliases] of Object.entries(MENU_ROUTE_ALIASES)) {
    if (aliases.some((alias) => matchesRoute(pathname, alias))) {
      return menuId
    }
  }

  return undefined
}

function whenCustomElementDefined(tagName: keyof HTMLElementTagNameMap): Promise<unknown> {
  if (!window.customElements?.whenDefined) {
    return Promise.resolve()
  }

  return window.customElements.whenDefined(tagName)
}

function AppRoutes() {
  return (
    <Routes>
      <Route path="/" element={<Navigate to="/visao-geral" replace />} />
      <Route path="/visao-geral" element={<VisaoGeral />} />
      <Route path="/dashboard" element={<Dashboard />} />
      <Route path="/listagem" element={<Listagem />} />
      <Route path="/lista-de-cards" element={<ListaDeCards />} />
      <Route path="/timeline" element={<Timeline />} />
      <Route path="/formulario" element={<Formulario />} />
      <Route path="/sem-registros" element={<SemRegistros />} />
      <Route path="/configuracoes" element={<Configuracoes />} />
      <Route path="/wizard" element={<Wizard />} />
      <Route path="/contexto" element={<SelecaoContexto />} />
      <Route path="*" element={<Navigate to="/visao-geral" replace />} />
    </Routes>
  )
}

function AppShell() {
  const appRef = useRef<HTMLBthAppElement | null>(null)
  const brandRef = useRef<HTMLBthMarcaProdutoElement | null>(null)
  const accountRef = useRef<HTMLBthContaUsuarioElement | null>(null)
  const utilitiesRef = useRef<HTMLBthUtilitariosElement | null>(null)
  const notificationsRef = useRef<HTMLBthNotificacoesElement | null>(null)
  const newsRef = useRef<HTMLBthNovidadesElement | null>(null)
  const navigate = useNavigate()
  const location = useLocation()

  const authorizationConfig = useMemo<AuthorizationConfig>(
    () => ({
      getAuthorization: () => AUTHORIZATION,
      handleUnauthorizedAccess: () =>
        new Promise((resolve) => {
          window.setTimeout(resolve, 3500)
        }),
    }),
    [],
  )

  useEffect(() => {
    const app = appRef.current

    if (!app) {
      return undefined
    }

    const handleMenuSelection = (event: Event) => {
      const { detail } = event as CustomEvent<OpcaoMenuSelecionadaEvent>
      const route = String(detail?.rota ?? '')

      if (route) {
        navigate(route)
      }
    }

    app.addEventListener('opcaoMenuSelecionada', handleMenuSelection)

    return () => {
      app.removeEventListener('opcaoMenuSelecionada', handleMenuSelection)
    }
  }, [navigate])

  useEffect(() => {
    const app = appRef.current
    let disposed = false

    if (!app) {
      return undefined
    }

    const configureRouteState = async () => {
      await whenCustomElementDefined('bth-app')

      if (disposed) {
        return
      }

      app.menuVertical = true
      app.opcoes = location.pathname === '/contexto' ? [] : MENU_OPTIONS

      const activeMenuId = findActiveMenuId(location.pathname)

      if (activeMenuId && typeof app.setMenuAtivo === 'function') {
        app.setMenuAtivo(activeMenuId)
      }
    }

    configureRouteState()

    return () => {
      disposed = true
    }
  }, [location.pathname])

  useEffect(() => {
    const brand = brandRef.current
    let disposed = false

    if (!brand) {
      return undefined
    }

    const configureBrand = async () => {
      await whenCustomElementDefined('bth-marca-produto')

      if (disposed) {
        return
      }

      brand.produto = 'React'
      brand.exibirProdutos = true
      brand.authorization = authorizationConfig
    }

    configureBrand()

    return () => {
      disposed = true
    }
  }, [authorizationConfig])

  useEffect(() => {
    const account = accountRef.current
    let disposed = false

    if (!account) {
      return undefined
    }

    const handleLogout = () => {
      console.debug('O usuário realizou a ação de logout no componente de conta do usuário')
    }

    account.addEventListener('logout', handleLogout)

    const configureAccount = async () => {
      await whenCustomElementDefined('bth-conta-usuario')

      if (disposed) {
        return
      }

      account.usuario = 'lorem.ipsum'
      account.nome = 'Lorem Ipsum'
      account.fotoUrl = 'https://placeimg.com/80/80/animals'
    }

    configureAccount()

    return () => {
      disposed = true
      account.removeEventListener('logout', handleLogout)
    }
  }, [])

  useEffect(() => {
    const utilities = utilitiesRef.current
    let disposed = false

    if (!utilities) {
      return undefined
    }

    const handleUtilitySelection = (event: Event) => {
      const { detail } = event as CustomEvent<OpcaoUtilitarioSelecionadaEvent>
      const route = String(detail?.rota ?? '')

      if (!route) {
        return
      }

      if (isAbsoluteUrl(route)) {
        window.open(route, '_blank', 'noopener,noreferrer')
        return
      }

      navigate(route)
    }

    utilities.addEventListener('opcaoUtilitarioSelecionada', handleUtilitySelection)

    const configureUtilities = async () => {
      await whenCustomElementDefined('bth-utilitarios')

      if (disposed) {
        return
      }

      utilities.utilitarios = UTILITY_OPTIONS
    }

    configureUtilities()

    return () => {
      disposed = true
      utilities.removeEventListener('opcaoUtilitarioSelecionada', handleUtilitySelection)
    }
  }, [navigate])

  useEffect(() => {
    const notifications = notificationsRef.current
    let disposed = false

    if (!notifications) {
      return undefined
    }

    const handleLinkedNotification = (event: Event) => {
      const { detail } = event as CustomEvent<NotificacaoComLinkEvent>
      console.log('Nova mensagem obtida no componente de notificações', detail)
    }

    notifications.addEventListener('novaNotificacaoComLink', handleLinkedNotification)

    const configureNotifications = async () => {
      await whenCustomElementDefined('bth-notificacoes')

      if (disposed) {
        return
      }

      notifications.authorization = authorizationConfig
    }

    configureNotifications()

    return () => {
      disposed = true
      notifications.removeEventListener('novaNotificacaoComLink', handleLinkedNotification)
    }
  }, [authorizationConfig])

  useEffect(() => {
    const news = newsRef.current
    let disposed = false

    if (!news) {
      return undefined
    }

    const configureNews = async () => {
      await whenCustomElementDefined('bth-novidades')

      if (disposed) {
        return
      }

      news.authorization = authorizationConfig
    }

    configureNews()

    return () => {
      disposed = true
    }
  }, [authorizationConfig])

  return (
    <bth-app ref={appRef} menu-vertical="">
      <bth-marca-produto ref={brandRef} slot="menu_marca_produto"></bth-marca-produto>

      <bth-utilitarios ref={utilitiesRef} slot="menu_ferramentas"></bth-utilitarios>
      <bth-ajuda slot="menu_ferramentas"></bth-ajuda>
      <bth-novidades ref={newsRef} slot="menu_ferramentas"></bth-novidades>
      <bth-notificacoes ref={notificationsRef} slot="menu_ferramentas"></bth-notificacoes>
      <bth-conta-usuario ref={accountRef} slot="menu_ferramentas"></bth-conta-usuario>

      <main slot="container_aplicacao" className="container-fluid px-3 mt-2">
        <AppRoutes />
      </main>
    </bth-app>
  )
}

function App() {
  return (
    <BrowserRouter>
      <AppShell />
    </BrowserRouter>
  )
}

export default App

// theme-bootstrap-4-angular/src/app/app.component.ts
import { Component, NgZone, ViewChild, ElementRef } from '@angular/core';
import { Router, NavigationEnd } from "@angular/router"

import { Authorization, AuthorizationConfig, OpcaoMenu, Utilitario, OpcaoMenuSelecionadaEvent, OpcaoUtilitarioSelecionadaEvent } from '@betha-plataforma/estrutura-componentes';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  @ViewChild('app', { static: true }) appElement: ElementRef<HTMLBthAppElement>;
  @ViewChild('marcaProduto', { static: true }) marcaProdutoElement: ElementRef<HTMLBthMarcaProdutoElement>;
  @ViewChild('contaUsuario', { static: true }) contaUsuarioElement: ElementRef<HTMLBthContaUsuarioElement>;
  @ViewChild('utilitarios', { static: true }) utilitariosElement: ElementRef<HTMLBthUtilitariosElement>;
  @ViewChild('notificacoes', { static: true }) notificacoesElement: ElementRef<HTMLBthNotificacoesElement>;
  @ViewChild('novidades', { static: true }) novidadesElement: ElementRef<HTMLBthNovidadesElement>;

  private opcoesMenu: Array<OpcaoMenu> = [
    { id: 'Menu0', descricao: 'Visão geral', icone: 'home', rota: '/', possuiPermissao: true },
    {
      id: '', descricao: 'Seções', icone: 'book-open-page-variant', possuiPermissao: true,
      submenus: [
        { id: 'menu3', descricao: 'Dashboard', rota: '/menu3', possuiPermissao: true },

        { id: 'menu4', descricao: 'Listagem', rota: '/menu4', possuiPermissao: true },
        { id: 'menu7', descricao: 'Lista de cards', rota: '/menu7', possuiPermissao: true },

        { id: 'menu1', descricao: 'Timeline', rota: '/menu1', possuiPermissao: true },
        { id: 'menu2', descricao: 'Formulário', rota: '/menu2', possuiPermissao: true },
        
        
        { id: 'menu5', descricao: 'Sem registros', rota: '/menu5', possuiPermissao: true },
        { id: 'menu6', descricao: 'Configurações', rota: '/menu6', possuiPermissao: true },
        
        //{ id: 'menu8', descricao: 'Wizard', rota: '/menu8', possuiPermissao: true }
      ]
    },
  ];

  private opcoesUtilitarios: Array<Utilitario> = [
    { nome: 'Gerenciador de Acessos', rota: '/menu3', icone: 'key-variant', possuiPermissao: true, },
    { nome: 'Link externo', rota: 'https://aws.amazon.com/pt/console/', icone: 'amazon', possuiPermissao: true },
    { nome: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit', rota: '/', icone: 'merge', possuiPermissao: true, },
  ]

  private authorization: AuthorizationConfig = {
    getAuthorization: this.getAuthorization,
    handleUnauthorizedAccess: this.handleUnauthorizedAccess,
  }

  constructor(public ngZone: NgZone, public router: Router) { }

  ngOnInit() {
    this.configurarApp();
    this.configurarMarcaProduto();
    this.configurarContaUsuario();
    this.configurarUtilitarios();
    this.configurarNotificacoes();
    this.configurarNovidades();
  }

  private getAuthorization(): Authorization {
    return {
      accessId: '5e613debe191120137316351',
      accessToken: 'fbbbbffd-eeb4-4f7c-b222-8097e55e28fa',
      systemId: 78
    };
  }

  async handleUnauthorizedAccess(): Promise<void> {
    return new Promise(function (resolve) {
      setTimeout(function () {
        resolve();
      }, 3500);
    });
  }

  isUrl(text) {
    try {
      new URL(text);
      return true;
    } catch {
      return false;
    }
  }

  private configurarApp() {
    this.appElement.nativeElement.opcoes = this.opcoesMenu;

    this.appElement.nativeElement.addEventListener('opcaoMenuSelecionada', (event: CustomEvent<OpcaoMenuSelecionadaEvent>) => {
      this.ngZone.run(() => {
        this.router.navigate([event.detail.rota]);
      });
    });

    this.setMenuAtivoPorRota(this.router.url);

    this.router.events.subscribe(routeEvent => {
      if (routeEvent instanceof NavigationEnd) {
        const route: NavigationEnd = routeEvent;
        if (route.url === '/contexto') {
          this.appElement.nativeElement.opcoes = [];
        } else {
            this.appElement.nativeElement.opcoes = this.opcoesMenu;
        }
        this.setMenuAtivoPorRota(route.url);
      }
    });
  }

  private setMenuAtivoPorRota(rota: string) {
    this.opcoesMenu.forEach(opcaoMenu => {
      if (opcaoMenu.rota === rota) {
        this.appElement.nativeElement.setMenuAtivo(opcaoMenu.id);
      }

      if (opcaoMenu.submenus) {
        opcaoMenu.submenus.forEach(submenu => {
          if (rota.includes(submenu.rota)) {
            this.appElement.nativeElement.setMenuAtivo(submenu.id);
          }
        });
      }
    })
  }

  private configurarMarcaProduto() {
    this.marcaProdutoElement.nativeElement.authorization = this.authorization;
  }

  private configurarContaUsuario() {
    this.contaUsuarioElement.nativeElement.addEventListener('logout', function logout() {
      console.debug('O usuário realizou a ação de logout no componente de conta do usuário');
    });
  }

  private configurarUtilitarios() {
    this.utilitariosElement.nativeElement.utilitarios = this.opcoesUtilitarios;

    this.utilitariosElement.nativeElement.addEventListener('opcaoUtilitarioSelecionada', (event: CustomEvent<OpcaoUtilitarioSelecionadaEvent>) => {
      this.ngZone.run(() => {
        if (this.isUrl(event.detail.rota)) {
          window.open(event.detail.rota, '_blank')
          return;
        }

        this.router.navigate([event.detail.rota]);
      });
    });
  }

  private configurarNotificacoes() {
    this.notificacoesElement.nativeElement.addEventListener('novaNotificacaoComLink', (data: CustomEvent) => {
      console.log('Nova mensagem obtida no componente de notificações', data.detail);
    });

    this.notificacoesElement.nativeElement.authorization = this.authorization;
  }

  private configurarNovidades() {
    this.novidadesElement.nativeElement.authorization = this.authorization;
  }

}

<bth-app menu-vertical #app>
  
  <bth-marca-produto slot="menu_marca_produto" produto="Angular" exibir-produtos #marcaProduto> </bth-marca-produto>

  <bth-utilitarios slot="menu_ferramentas" #utilitarios></bth-utilitarios>
  <bth-ajuda slot="menu_ferramentas"></bth-ajuda>
  <bth-novidades slot="menu_ferramentas" #novidades></bth-novidades>
  <bth-notificacoes slot="menu_ferramentas" #notificacoes></bth-notificacoes>
  <bth-conta-usuario slot="menu_ferramentas" usuario="lorem.ipsum" nome="Lorem Ipsum" foto-url="https://placeimg.com/80/80/animals" #contaUsuario> </bth-conta-usuario>

  <main slot="container_aplicacao" class="container-fluid mt-2">
    <router-outlet></router-outlet>
  </main>

</bth-app>
