// theme-bootstrap-4-angular/src/app/app.component.ts
import { Component, NgZone, ViewChild, ElementRef } from '@angular/core';
import { Router, NavigationEnd } from "@angular/router"

import { Authorization, AuthorizationConfig, OpcaoMenu, Utilitario, OpcaoMenuSelecionadaEvent, OpcaoUtilitarioSelecionadaEvent } from '@betha-plataforma/estrutura-componentes';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  @ViewChild('app', { static: true }) appElement: ElementRef<HTMLBthAppElement>;
  @ViewChild('marcaProduto', { static: true }) marcaProdutoElement: ElementRef<HTMLBthMarcaProdutoElement>;
  @ViewChild('contaUsuario', { static: true }) contaUsuarioElement: ElementRef<HTMLBthContaUsuarioElement>;
  @ViewChild('utilitarios', { static: true }) utilitariosElement: ElementRef<HTMLBthUtilitariosElement>;
  @ViewChild('notificacoes', { static: true }) notificacoesElement: ElementRef<HTMLBthNotificacoesElement>;
  @ViewChild('novidades', { static: true }) novidadesElement: ElementRef<HTMLBthNovidadesElement>;

  private opcoesMenu: Array<OpcaoMenu> = [
    { id: 'listagem', descricao: 'Listagem', icone: 'view-list', rota: '/', possuiPermissao: true },
    {
      id: '', descricao: 'Menu 2', icone: 'cog', possuiPermissao: true,
      submenus: [
        { id: 'menu2', descricao: 'Submenu 1', rota: '/menu2', possuiPermissao: true },
        { id: 'menu3', descricao: 'Submenu 2', rota: '/menu3', possuiPermissao: true },
      ]
    },
  ];

  private opcoesUtilitarios: Array<Utilitario> = [
    { nome: 'Gerenciador de Acessos', rota: '/menu3', icone: 'key-variant', possuiPermissao: true, },
    { nome: 'Link externo', rota: 'https://aws.amazon.com/pt/console/', icone: 'amazon', possuiPermissao: true },
    { nome: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit', rota: '/', icone: 'merge', possuiPermissao: true, },
  ]

  private authorization: AuthorizationConfig = {
    getAuthorization: this.getAuthorization,
    handleUnauthorizedAccess: this.handleUnauthorizedAccess,
  }

  constructor(public ngZone: NgZone, public router: Router) { }

  ngOnInit() {
    this.configurarApp();
    this.configurarMarcaProduto();
    this.configurarContaUsuario();
    this.configurarUtilitarios();
    this.configurarNotificacoes();
    this.configurarNovidades();
  }

  private getAuthorization(): Authorization {
    return {
      accessId: '5e613debe191120137316351',
      accessToken: 'fbbbbffd-eeb4-4f7c-b222-8097e55e28fa',
      systemId: 78
    };
  }

  async handleUnauthorizedAccess(): Promise<void> {
    return new Promise(function (resolve) {
      setTimeout(function () {
        resolve();
      }, 3500);
    });
  }

  isUrl(text) {
    try {
      new URL(text);
      return true;
    } catch {
      return false;
    }
  }

  private configurarApp() {
    this.appElement.nativeElement.opcoes = this.opcoesMenu;

    this.appElement.nativeElement.addEventListener('opcaoMenuSelecionada', (event: CustomEvent<OpcaoMenuSelecionadaEvent>) => {
      this.ngZone.run(() => {
        this.router.navigate([event.detail.rota]);
      });
    });

    this.setMenuAtivoPorRota(this.router.url);

    this.router.events.subscribe(routeEvent => {
      if (routeEvent instanceof NavigationEnd) {
        const route: NavigationEnd = routeEvent;
        this.setMenuAtivoPorRota(route.url);
      }
    });
  }

  private setMenuAtivoPorRota(rota: string) {
    this.opcoesMenu.forEach(opcaoMenu => {
      if (opcaoMenu.rota === rota) {
        this.appElement.nativeElement.setMenuAtivo(opcaoMenu.id);
      }

      if (opcaoMenu.submenus) {
        opcaoMenu.submenus.forEach(submenu => {
          if (rota.includes(submenu.rota)) {
            this.appElement.nativeElement.setMenuAtivo(submenu.id);
          }
        });
      }
    })
  }

  private configurarMarcaProduto() {
    this.marcaProdutoElement.nativeElement.authorization = this.authorization;
  }

  private configurarContaUsuario() {
    this.contaUsuarioElement.nativeElement.addEventListener('logout', function logout() {
      console.debug('O usuário realizou a ação de logout no componente de conta do usuário');
    });
  }

  private configurarUtilitarios() {
    this.utilitariosElement.nativeElement.utilitarios = this.opcoesUtilitarios;

    this.utilitariosElement.nativeElement.addEventListener('opcaoUtilitarioSelecionada', (event: CustomEvent<OpcaoUtilitarioSelecionadaEvent>) => {
      this.ngZone.run(() => {
        if (this.isUrl(event.detail.rota)) {
          window.open(event.detail.rota, '_blank')
          return;
        }

        this.router.navigate([event.detail.rota]);
      });
    });
  }

  private configurarNotificacoes() {
    this.notificacoesElement.nativeElement.addEventListener('novaNotificacaoComLink', (data: CustomEvent) => {
      console.log('Nova mensagem obtida no componente de notificações', data.detail);
    });

    this.notificacoesElement.nativeElement.authorization = this.authorization;
  }

  private configurarNovidades() {
    this.novidadesElement.nativeElement.authorization = this.authorization;
  }

}

<bth-app menu-vertical #app>
  
  <bth-marca-produto slot="menu_marca_produto" produto="Angular" exibir-produtos #marcaProduto> </bth-marca-produto>

  <bth-utilitarios slot="menu_ferramentas" #utilitarios></bth-utilitarios>
  <bth-ajuda slot="menu_ferramentas"></bth-ajuda>
  <bth-novidades slot="menu_ferramentas" #novidades></bth-novidades>
  <bth-notificacoes slot="menu_ferramentas" #notificacoes></bth-notificacoes>
  <bth-conta-usuario slot="menu_ferramentas" usuario="lorem.ipsum" nome="Lorem Ipsum" foto-url="https://placeimg.com/80/80/animals" #contaUsuario> </bth-conta-usuario>

  <main slot="container_aplicacao" class="container-fluid mt-2">
    <router-outlet></router-outlet>
  </main>

</bth-app>

// estrutura-componentes-vue/src/App.vue
<template>
  <bth-app menu-vertical>
    <bth-marca-produto slot="menu_marca_produto" produto="Vue" exibir-produtos> </bth-marca-produto>

    <bth-utilitarios slot="menu_ferramentas"></bth-utilitarios>
    <bth-ajuda slot="menu_ferramentas"></bth-ajuda>
    <bth-novidades slot="menu_ferramentas"></bth-novidades>
    <bth-notificacoes slot="menu_ferramentas"></bth-notificacoes>
    <bth-conta-usuario slot="menu_ferramentas" usuario="lorem.ipsum" nome="Lorem Ipsum" foto-url="https://placeimg.com/80/80/animals"> </bth-conta-usuario>

    <main slot="container_aplicacao" class="container-fluid mt-2">
      <router-view />
    </main>
  </bth-app>

</template>

<script lang="ts">
import Vue from "vue";

import router from './router'

import { Authorization, OpcaoMenu, Utilitario, OpcaoMenuSelecionadaEvent, OpcaoUtilitarioSelecionadaEvent} from '@betha-plataforma/estrutura-componentes';

const opcoesMenu: Array<OpcaoMenu> =  [
  { id: 'menu1', descricao: 'Menu 1', icone: 'chart-pie', rota: '/', possuiPermissao: true },
  {
    id: '', descricao: 'Menu 2', icone: 'cog', possuiPermissao: true,
    submenus: [
      { id: 'menu2', descricao: 'Submenu 1', rota: '/menu2', possuiPermissao: true },
      { id: 'menu3', descricao: 'Submenu 2', rota: '/menu3', possuiPermissao: true },
    ]
  },
];

const opcoesUtilitarios: Array<Utilitario> = [
  { nome: 'Gerenciador de Acessos', rota: '/menu3', icone: 'key-variant', possuiPermissao: true, },
  { nome: 'Link externo', rota: 'https://aws.amazon.com/pt/console/', icone: 'amazon', possuiPermissao: true },
  { nome: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit', rota: '/', icone: 'merge', possuiPermissao: true, },
];

let menuElement: HTMLBthAppElement;

export default Vue.extend({
  created: async function() {
    await customElements.whenDefined('bth-app');

    this.configurarApp();
    this.configurarMarcaProduto();
    this.configurarContaUsuario();
    this.configurarUtilitarios();
    this.configurarNotificacoes();
    this.configurarNovidades();
  },
  watch: {
    $route(to) {
      this.setMenuAtivoPorRota(to.path);
    }
  },
  methods: {
   configurarApp() {
      menuElement = document.querySelector('bth-app');
      menuElement.opcoes = opcoesMenu;

      // TODO: Entender pq o Vue não consegue importar a interface do CustomEvent<OpcaoMenuSelecionadaEvent>
      // eslint-disable-next-line
      menuElement.addEventListener('opcaoMenuSelecionada', (event: any) => {
        const detail: OpcaoMenuSelecionadaEvent = event.detail;

        try {
          router.push(detail.rota);
        } catch  {
          // nothing
        }
      });

      this.setMenuAtivoPorRota(router.currentRoute.path);
    },
    setMenuAtivoPorRota(rota: string) {
      opcoesMenu.forEach(opcaoVertical => {
        if (opcaoVertical.rota === rota) {
          menuElement.setMenuAtivo(opcaoVertical.id);
        }

        if (opcaoVertical.submenus) {
          opcaoVertical.submenus.forEach(submenu => {
            if (rota.includes(submenu.rota)) {
              menuElement.setMenuAtivo(submenu.id);
            }
          });
        }
      });
    },
    configurarMarcaProduto() {
      const marcaProdutoElement: HTMLBthMarcaProdutoElement = document.querySelector('bth-marca-produto');

      marcaProdutoElement.authorization = {
        getAuthorization: this.getAuthorization,
        handleUnauthorizedAccess: this.handleUnauthorizedAccess,
      };
    },
    configurarContaUsuario() {
      const contaUsuarioElement: HTMLBthContaUsuarioElement = document.querySelector('bth-conta-usuario');

      contaUsuarioElement.addEventListener('logout', function logout() {
        // eslint-disable-next-line no-console
        console.debug('O usuário realizou a ação de logout no componente de conta do usuário');
      });
    },
    configurarUtilitarios() {
      const utilitariosElement: HTMLBthUtilitariosElement = document.querySelector('bth-utilitarios');

      utilitariosElement.utilitarios = opcoesUtilitarios;

      // TODO: Entender pq o Vue não consegue importar a interface do CustomEvent<OpcaoUtilitarioSelecionadaEvent>
      // eslint-disable-next-line
      utilitariosElement.addEventListener('opcaoUtilitarioSelecionada', (event: any) => {
        const detail: OpcaoUtilitarioSelecionadaEvent = event.detail;

        if (this.isUrl(detail.rota)) {
          window.open(detail.rota, '_blank')
          return;
        }

        router.push(detail.rota);
      });
    },
    configurarNotificacoes() {
      const notificacoesElement: HTMLBthNotificacoesElement = document.querySelector('bth-notificacoes');

      notificacoesElement.addEventListener('novaNotificacaoComLink', (data) => {
        // eslint-disable-next-line no-console
        console.log('Nova mensagem obtida no componente de notificações', data);
      });

      notificacoesElement.authorization = {
        getAuthorization: this.getAuthorization,
        handleUnauthorizedAccess: this.handleUnauthorizedAccess,
      };
    },
    configurarNovidades() {
      const novidadesElement: HTMLBthNovidadesElement = document.querySelector('bth-novidades');

      novidadesElement.authorization = {
        getAuthorization: this.getAuthorization,
        handleUnauthorizedAccess: this.handleUnauthorizedAccess,
      };
    },
    getAuthorization(): Authorization {
      return {
        accessId: "5e613debe191120137316351",
        accessToken: "fbbbbffd-eeb4-4f7c-b222-8097e55e28fa",
        systemId: 78
      };
    },
    async handleUnauthorizedAccess(): Promise<void> {
      return new Promise(function(resolve) {
        setTimeout(function() {
          resolve();
        }, 3500);
      });
    },
    isUrl(text: string): boolean {
      try {
        new URL(text);
        return true;
      } catch {
        return false;
      }
    },
  }
});
</script>
