// react/src/pages/ListaDeCards.tsx
import { useState } from 'react'
import { Dropdown, Modal, ProgressBar } from 'react-bootstrap'
import { CARD_AVATARS, FILE_CARDS } from '../data/examples'
import { LoadingOverlay, MdiIcon, PageHeader } from './shared'

type ModalProps = {
  show: boolean
  onHide: () => void
}

function FileActions({ id }: { id: number }) {
  return (
    <Dropdown align="end" className="d-inline-block">
      <Dropdown.Toggle
        variant="link"
        size="sm"
        className="no-caret"
        id={`arquivo-acoes-${id}`}
        aria-label="Abrir ações do arquivo"
      >
        <MdiIcon name="dots-vertical" />
      </Dropdown.Toggle>
      <Dropdown.Menu>
        <Dropdown.Item as="button" type="button">
          <MdiIcon name="pencil" className="me-2" />
          Editar
        </Dropdown.Item>
        <Dropdown.Divider />
        <Dropdown.Item as="button" type="button">
          <MdiIcon name="trash-can-outline" className="me-2" />
          Excluir
        </Dropdown.Item>
      </Dropdown.Menu>
    </Dropdown>
  )
}

function FileModal({ show, onHide }: ModalProps) {
  return (
    <Modal show={show} onHide={onHide}>
      <Modal.Header closeButton>
        <Modal.Title as="h4">Salvando arquivo</Modal.Title>
      </Modal.Header>

      <form>
        <Modal.Body>
          <div className="row">
            <div className="col-12">
              <label className="visually-hidden" htmlFor="anexoInputModal">
                Arquivo
              </label>
              <div className="input-group">
                <input
                  id="anexoInputModal"
                  type="text"
                  className="form-control"
                  placeholder="Escolha um arquivo de seu dispositivo"
                  aria-label="Escolha um arquivo de seu dispositivo"
                  disabled
                />
                <label className="btn btn-secondary px-3 position-relative btn-sm" htmlFor="btnAnexoModal">
                  <input id="btnAnexoModal" className="visually-hidden" type="file" />
                  <MdiIcon name="paperclip" />
                  <span className="visually-hidden">Selecionar arquivo</span>
                </label>
              </div>
            </div>

            <div className="col-12 py-3">
              <ProgressBar now={80} />
              <p className="m-0 mt-1 text-muted">Carregando...</p>
            </div>
          </div>
        </Modal.Body>

        <Modal.Footer>
          <button type="button" className="btn btn-primary" onClick={onHide}>
            Salvar
          </button>
          <button type="button" className="btn btn-secondary" onClick={onHide}>
            Cancelar
          </button>
        </Modal.Footer>
      </form>
    </Modal>
  )
}

export function ListaDeCards() {
  const [showModal, setShowModal] = useState(false)

  return (
    <>
      <LoadingOverlay />
      <PageHeader title="Lista de cards">
        <div className="col-12 col-lg-auto my-3 my-lg-0">
          <nav aria-label="breadcrumb">
            <ol className="breadcrumb">
              <li className="breadcrumb-item">
                <button type="button" className="btn btn-link p-0">
                  Grupo
                </button>
              </li>
              <li className="breadcrumb-item">
                <button type="button" className="btn btn-link p-0">
                  Subgrupo
                </button>
              </li>
              <li className="breadcrumb-item active" aria-current="page">
                Item
              </li>
            </ol>
          </nav>
        </div>
      </PageHeader>

      <div className="row align-items-center mb-3">
        <div className="col">
          <div className="btn-group">
            <button
              type="button"
              className="btn btn-sm btn-success"
              onClick={() => setShowModal(true)}
              aria-label="Adicionar arquivo"
            >
              <MdiIcon name="plus" className="h6 m-0 me-1" />
              Arquivo
            </button>
          </div>
        </div>

        <div className="col-auto">
          <div className="d-block pe-1">
            {CARD_AVATARS.map((avatar) => (
              <div className="d-inline-block me-n1" key={avatar}>
                <img className="rounded-circle border" width="30" height="30" alt="" src={avatar} />
              </div>
            ))}
          </div>
        </div>

        <div className="col-12 col-lg-3 my-3 my-lg-0">
          <label className="visually-hidden" htmlFor="buscaCards">
            Pesquisar na lista de cards
          </label>
          <div className="input-group">
            <input
              id="buscaCards"
              className="form-control"
              type="search"
              placeholder="O que você está buscando?"
            />
            <button type="button" className="btn btn-secondary" aria-label="Pesquisar">
              <MdiIcon name="magnify" />
            </button>
          </div>
        </div>
      </div>

      <div className="row">
        {FILE_CARDS.map((file) => (
          <div className="col-12 col-sm-6 col-md-3 col-lg-2" key={file.id}>
            <div className="card mb-2">
              <div className="card-body p-0 overflow-hidden file-card-preview">
                <img className="w-100 file-card-image" src={file.imageUrl} alt="" />
              </div>
              <div className="card-footer bg__gray--l40">
                <div className="row m-0 align-items-center">
                  <div className="col-10">
                    <p className="text-truncate m-0">{file.title}</p>
                  </div>
                  <div className="col-2 text-end">
                    <FileActions id={file.id} />
                  </div>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>

      <FileModal show={showModal} onHide={() => setShowModal(false)} />
    </>
  )
}

// theme-bootstrap-5-angular-v21/src/app/lista-de-cards/lista-de-cards.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  TemplateRef,
  inject,
  viewChild,
} from '@angular/core';
import {
  NgbDropdownModule,
  NgbModal,
  NgbModalModule,
  NgbProgressbarModule,
} from '@ng-bootstrap/ng-bootstrap';

interface ArquivoCard {
  readonly id: number;
  readonly imagemUrl: string;
  readonly titulo: string;
}

@Component({
  selector: 'app-lista-de-cards',
  imports: [NgbDropdownModule, NgbModalModule, NgbProgressbarModule],
  templateUrl: './lista-de-cards.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ListaDeCardsComponent {
  private readonly modalService = inject(NgbModal);
  private readonly modalTemplate = viewChild.required<TemplateRef<unknown>>('registerModal');

  protected readonly avatares: readonly string[] = [
    'https://picsum.photos/id/220/60',
    'https://picsum.photos/id/221/60',
    'https://picsum.photos/id/222/60',
    'https://picsum.photos/id/223/60',
  ];

  protected readonly arquivos: readonly ArquivoCard[] = [
    { id: 1, imagemUrl: 'https://picsum.photos/id/230/400/320', titulo: 'Este é um arquivo' },
    { id: 2, imagemUrl: 'https://picsum.photos/id/231/400/320', titulo: 'Este é um arquivo' },
    { id: 3, imagemUrl: 'https://picsum.photos/id/232/400/320', titulo: 'Este é um arquivo' },
    { id: 4, imagemUrl: 'https://picsum.photos/id/233/400/320', titulo: 'Este é um arquivo' },
    { id: 5, imagemUrl: 'https://picsum.photos/id/234/400/320', titulo: 'Este é um arquivo' },
    { id: 6, imagemUrl: 'https://picsum.photos/id/235/400/320', titulo: 'Este é um arquivo' },
    { id: 7, imagemUrl: 'https://picsum.photos/id/236/400/320', titulo: 'Este é um arquivo' },
    { id: 8, imagemUrl: 'https://picsum.photos/id/238/400/320', titulo: 'Este é um arquivo' },
  ];

  protected abrirModal(): void {
    this.modalService.open(this.modalTemplate());
  }
}

<div class="spinner-grow-backdrop loader-fadeout">
  <div class="spinner-grow"></div>
</div>

<ng-template #registerModal let-modal>
  <div class="modal-header">
    <h4 class="modal-title">Salvando arquivo</h4>
    <button
      type="button"
      class="btn-close"
      aria-label="Close"
      (click)="modal.dismiss('Cross click')"
    ></button>
  </div>

  <form>
    <div class="modal-body">
      <div class="row">
        <div class="col-12">
          <label class="visually-hidden" for="anexoInputModal">Arquivo</label>
          <div class="input-group">
            <input
              id="anexoInputModal"
              type="text"
              class="form-control"
              placeholder="Escolha um arquivo de seu dispositivo"
              aria-label="Escolha um arquivo de seu dispositivo"
              [disabled]="true"
            />
            <label class="btn btn-secondary px-3 position-relative btn-sm" for="btnAnexoModal">
              <input id="btnAnexoModal" class="visually-hidden" type="file" />
              <i class="mdi mdi-paperclip" aria-hidden="true"></i>
              <span class="visually-hidden">Selecionar arquivo</span>
            </label>
          </div>
        </div>

        <div class="col-12 py-3">
          <ngb-progressbar [value]="80"></ngb-progressbar>
          <p class="m-0 mt-1 text-muted">Carregando...</p>
        </div>
      </div>
    </div>

    <div class="modal-footer">
      <button type="button" class="btn btn-primary" (click)="modal.close('Save click')">Salvar</button>
      <button type="button" class="btn btn-secondary" (click)="modal.close()">Cancelar</button>
    </div>
  </form>
</ng-template>

<div class="row align-items-center py-3">
  <div class="col">
    <h4 class="m-0">Lista de cards</h4>
  </div>
  <div class="col-12 col-lg-auto my-3 my-lg-0">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><button type="button" class="btn btn-link p-0">Grupo</button></li>
        <li class="breadcrumb-item"><button type="button" class="btn btn-link p-0">Subgrupo</button></li>
        <li class="breadcrumb-item active" aria-current="page">Item</li>
      </ol>
    </nav>
  </div>
</div>

<div class="row align-items-center mb-3">
  <div class="col">
    <div class="btn-group">
      <button type="button" class="btn btn-sm btn-success" (click)="abrirModal()" aria-label="Adicionar arquivo">
        <i class="mdi mdi-plus h6 m-0 me-1" aria-hidden="true"></i>Arquivo
      </button>
    </div>
  </div>

  <div class="col-auto">
    <div class="d-block pe-1">
      @for (avatar of avatares; track avatar) {
        <div class="d-inline-block me-n1">
          <img class="rounded-circle border" width="30" height="30" alt="" [src]="avatar" />
        </div>
      }
    </div>
  </div>

  <div class="col-12 col-lg-3 my-3 my-lg-0">
    <label class="visually-hidden" for="buscaCards">Pesquisar na lista de cards</label>
    <div class="input-group">
      <input
        id="buscaCards"
        class="form-control"
        type="search"
        placeholder="O que você está buscando?"
      />
      <button type="button" class="btn btn-secondary" aria-label="Pesquisar">
        <i class="mdi mdi-magnify" aria-hidden="true"></i>
      </button>
    </div>
  </div>
</div>

<div class="row">
  @for (arquivo of arquivos; track arquivo.id) {
    <div class="col-12 col-sm-6 col-md-3 col-lg-2">
      <div class="card mb-2">
        <div class="card-body p-0 overflow-hidden" style="height: 180px;">
          <img
            class="w-100"
            style="height: 180px; object-fit: cover;"
            [src]="arquivo.imagemUrl"
            alt=""
          />
        </div>
        <div class="card-footer bg__gray--l40">
          <div class="row m-0 align-items-center">
            <div class="col-10">
              <p class="text-truncate m-0">{{ arquivo.titulo }}</p>
            </div>
            <div class="col-2 text-end">
              <div ngbDropdown class="d-inline-block">
                <button
                  class="btn btn-sm btn-link"
                  [attr.id]="'arquivo-acoes-' + arquivo.id"
                  ngbDropdownToggle
                  aria-label="Abrir ações do arquivo"
                >
                  <i class="mdi mdi-dots-vertical" aria-hidden="true"></i>
                </button>
                <div ngbDropdownMenu [attr.aria-labelledby]="'arquivo-acoes-' + arquivo.id">
                  <button ngbDropdownItem type="button">
                    <i class="mdi mdi-pencil me-2" aria-hidden="true"></i>Editar
                  </button>
                  <div class="dropdown-divider"></div>
                  <button ngbDropdownItem type="button">
                    <i class="mdi mdi-trash-can-outline me-2" aria-hidden="true"></i>Excluir
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  }
</div>
