// app-vue/src/components/ItemActions.vue
<template>
  <div class="dropdown d-inline-block">
    <button
      type="button"
      class="btn btn-link no-caret btn-sm"
      :id="`item-acoes-${id}`"
      :aria-label="ariaLabel"
      data-bs-toggle="dropdown"
      aria-expanded="false"
    >
      <MdiIcon name="dots-vertical" />
    </button>
    <ul class="dropdown-menu dropdown-menu-end" :aria-labelledby="`item-acoes-${id}`">
      <li>
        <button type="button" class="dropdown-item">
          <MdiIcon name="pencil" extra-class="me-2" />
          Editar
        </button>
      </li>
      <li><hr class="dropdown-divider" /></li>
      <li>
        <button type="button" class="dropdown-item">
          <MdiIcon name="trash-can-outline" extra-class="me-2" />
          Excluir
        </button>
      </li>
    </ul>
  </div>
</template>

<script setup lang="ts">
import MdiIcon from './MdiIcon.vue'

withDefaults(defineProps<{ id: number; ariaLabel?: string }>(), { ariaLabel: 'Abrir ações' })
</script>

// app-react/src/components/ItemActions.tsx
import { Dropdown } from 'react-bootstrap'
import { MdiIcon } from './shared'

type ItemActionsProps = {
  id: number
  ariaLabel?: string
  size?: 'sm' | 'lg'
}

export function ItemActions({ id, ariaLabel = 'Abrir ações', size }: ItemActionsProps) {
  return (
    <Dropdown align="end" className="d-inline-block">
      <Dropdown.Toggle
        variant="link"
        size={size}
        className="no-caret"
        id={`item-acoes-${id}`}
        aria-label={ariaLabel}
      >
        <MdiIcon name="dots-vertical" />
      </Dropdown.Toggle>
      <Dropdown.Menu>
        <Dropdown.Item as="button" type="button">
          <MdiIcon name="pencil" className="me-2" />
          Editar
        </Dropdown.Item>
        <Dropdown.Divider />
        <Dropdown.Item as="button" type="button">
          <MdiIcon name="trash-can-outline" className="me-2" />
          Excluir
        </Dropdown.Item>
      </Dropdown.Menu>
    </Dropdown>
  )
}
